name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: configure
        run: chmod +x configure 
            ./configure
      - name: make
        run: make
      - uses: actions/upload-artifact@v2
        with:
          path: build/
          name: artifact_test.tar.gz
